# This file details the various servers in each environment which tests for this service require.
dev_int:
  servers:
    api: https://api.dev.bbbtest2.com/service/catalogue/
    search: https://api.dev.bbbtest2.com/service/search/

local:
  servers:
    api: http://localhost:7001/catalogue/
    search: http://localhost:9595/catalogue/search/
